### ISSUE TITLE
cromwell-tools does not support python3.5

### ISSUE THREAD

**Issue by fuego0607** [broadinstitute/cromwell-tools#104]
Problem:
I'm trying to use cromwell-tools in a project that is built to support python3.5 (currently the minimum python3 version available on the hosts I'm targeting). When trying to execute there are syntax errors within the cromwell-tools distribution due to the use of `f` strings, which are a python3.6 feature.

Looking at closed issue tickets, as well as the PR for refactoring to remove support for python2, it looks like python3.5 was mentioned as a minimum supported version. Links to these items here:
https://github.com/broadinstitute/cromwell-tools/issues/26
https://github.com/broadinstitute/cromwell-tools/pull/43

Proposed Solutions:
1. Update code to support python3.5 (and possibly other earlier versions) by removing the use of `f` strings.
2. Update documentation to specify that python3.6 is the minimum supported version as opposed to simply python3. Additionally, include `python_requires>=3.6` in the setup call in `setup.py`

**Comment by rexwangcc** [comment]
@fuego0607 Thanks for reporting the issue! As you mentioned we made the decision to switch to Python3.6 from Py2 a while ago. Since the only major difference between 3.5 and 3.6 is the f-strings, either of your proposed solutions is not difficult to implement. That said, do you or other uses have a preference on which you want to see happens?

**Comment by fuego0607** [comment]
@rexwangcc Thanks for replying back!

I may be a bit biased due to the environment I'm working with, but I'm for supporting 3.5. The use of f-strings is mostly a convenience and something that is simple to replace. However, in addition to that, I think it makes sense as 3.5 does not reach end of life until 2020-09-13 (https://devguide.python.org/#status-of-python-branches).

Whichever way is decided I would be happy to make the changes and submit a PR.

**Comment by rexwangcc** [comment]
@fuego0607 Thanks, what you mentioned makes sense to me. Please feel free to assign this issue to yourself if you have time, or I will pick it up later this week. :octocat:
