### ISSUE TITLE
Move Cost script to cromwell tools

### ISSUE THREAD

**Issue by kbergin** [broadinstitute/cromwell-tools#12]
We (mint team) should make a pull request to add our version of the cost script (currently in skylab) to cromwell-tools.

~It currently lives here:
https://github.com/HumanCellAtlas/skylab/blob/master/smartseq2_single_sample/run_multi_samples/scripts/calculate_cost_workflow.py~

_Kylee is moving tickets from mint backlog into cromwell-tools issues_

**Comment by danxmoran** [comment]
@kbergin, @benjamincarlin and I would be interested in helping out with this. The link above 404s now; did the script move elsewhere? If it's been deleted, could we patch in [green's version](https://github.com/broadinstitute/dsde-pipelines/blob/develop/scripts/calculate_cost.py) of the script?

**Comment by kbergin** [comment]
@danxmoran Great to hear! @rexwangcc is working on a large refactor of cromwell-tools that we left open a while ago. I'm not sure if that will or has effected this effort. Good point about the link being broken. Now I can't find it in any of our repos. Rex, do you know where this script lives now? I know we had one that was either based off of green's or the same as green's, not sure how it ended up.

**Comment by rexwangcc** [comment]
I have no idea where's the script moved to now, but we can get it by going to a specific pinned version of skylab: https://github.com/HumanCellAtlas/skylab/blob/v0.1.0/smartseq2_single_sample/run_multi_samples/scripts/calculate_cost_workflow.py

**Comment by rexwangcc** [comment]
@danxmoran @benjamincarlin Note that I'm working on a big refactor of the cromwell-tools, so your code might be moved around after the refactor
