### ISSUE TITLE
Harden Cromwell Manager

### ISSUE THREAD

**Issue by kbergin** [broadinstitute/cromwell-tools#13]
Ambrose made a package in https://github.com/ambrosejcarr/cromwell-manager/
with some example notebooks here, including the ones Ambrose demoed: https://github.com/ambrosejcarr/cromwell-manager/tree/master/src/examples

He has said there is some work to be done to make this package hardened and tested enough to be in a broad official repo. 

AC:
Harden with code review help

**Comment by rexwangcc** [comment]
Since the refactor of Cromwell-tools is done, let's close this ticket.
