### ISSUE TITLE
Merge Cromwell Manager into Cromwell Tools

### ISSUE THREAD

**Issue by kbergin** [broadinstitute/cromwell-tools#15]
We wrote a manager tool (https://github.com/ambrosejcarr/cromwell-manager/) for cromwell to help launch and manage workflows, which aids comp-bio development of pipelines. We can merge this into cromwell-tools. 

Can this be renamed to not use the word manager because the job manager also uses that word and it could get confusing?

AC: 
- PR of cromwell manager against cromwell-tools

**Comment by rexwangcc** [comment]
@ambrosejcarr Is there more work need to be done with this issue? Should we close this?

**Comment by ambrosejcarr** [comment]
`cromwell-tools` feels fully featured to me. I added a maintenance warning to `cromwell-manager` that redirects to `cromwell-tools`: [05779a0](https://github.com/ambrosejcarr/cromwell-manager/commit/05779a0f46e5109eaa9bc07670b97bd7a898b357).

I think this can be closed.

**Comment by rexwangcc** [comment]
Thanks, closing.
