### ISSUE TITLE
Add Quay autobuild to support testing-in-docker

### ISSUE THREAD

**Issue by ambrosejcarr** [broadinstitute/cromwell-tools#28]
Validate requires a copy of womtool. To do this, we need to get our docker image into the cloud. @rexwangcc Are you up for this?

**Comment by rexwangcc** [comment]
I will start working on this issue once I get permissions on quay.io

**Comment by rexwangcc** [comment]
Done: https://quay.io/repository/broadinstitute/cromwell-tools?tab=tags

**Comment by rexwangcc** [comment]
Done: https://quay.io/repository/broadinstitute/cromwell-tools?tab=tags
