### ISSUE TITLE
Add a "validate" command?

### ISSUE THREAD

**Issue by danxmoran** [broadinstitute/cromwell-tools#38]
On Green (and soon on Monster), CI for WDL development follows the pattern:
1. Run a WDL against some collection of input JSONs
2. Wait for all the runs to complete
3. Feed the outputs of each run into a "validation WDL", along with a corresponding set of "truth" inputs
4. Wait for all the validation runs to complete

The test runner has typically had special knowledge about each pipeline, but it feels like it should be possible to generate the core functionality.

I'm not sure if cromwell-tools would be the best place for that functionality to live (maybe there could be a new `cromwell-test-tools` package?), but here's an idea for what the command might look like:
```
$> cromwell-tools validate -h
usage: cromwell-tools validate [-h] [-c CROMWELL_URL] [-u USERNAME] [-p PASSWORD]
                               [-s SECRETS_FILE]
                               --wdl-file WDL_FILE
                               --validation-wdl-file WDL_FILE
                               [--dependencies-json DEPENDENCIES_JSON]
                               --inputs-batch INPUTS_JSON1:TRUTH_OUTPUTS1
                               [--inputs-batch INPUTS_JSON2:TRUTH_OUTPUTS2 ...]
                               --inputs-json INPUTS_JSON
                               [--inputs2-json INPUTS2_JSON]
                               [--options-file OPTIONS_FILE]
```
The command would do something like:
1. Parse the `inputs-json`s out of each `inputs-batch` arg
2. Submit each input along with `wdl-file`, `dependencies-json`, `inputs2-json`, and `options-file` using the existing `submit` logic
3. Wait for each workflow to finish using the existing `wait` logic
4. Query the outputs of each workflow, getting something like:
    ```json
     {
       "MyMainWorkflow.out1": "gs://....",
       "MyMainWorkflow.out2": 10
     }
    ```
5. Strip the main workflow's name from the outputs, and combine with the truth outputs to build an input JSON for the validation WDL:
    ```json
    {
      "ValidateMyMainWorkflow.test": {
        "out1": "gs://....",
        "out2": 10
      },
      "ValidateMyMainWorkflow.truth": {
        "out1": "gs://....",
        "out2": 20
      }
    }
    ```
6. Run the validation WDL on each of these constructed inputs using the existing `submit` logic
7. Wait for each validation run to finish using the existing `wait` logic

Does this sound like logic that'd make sense to live in `cromwell-tools`? I'd be happy to put a PR together for it if so.

**Comment by rexwangcc** [comment]
Generally it looks like a great feature to have, I have some detailed questions:
1. Personally, I figured `validate` implies more about "validate inputs for a workflow", and it doesn't need to concern about the results once we submit the workflow, `wait` and probably `validate-results`/`validate-outputs` should take care "validate outputs for a workflow".

2. In the `The command would do something like:` section, 1-4 are very reasonable and consistent with where we want this lib to go. I have some concerns about 5-7 though:
    - Adding the ability to start a validation WDL will introduce extra dependencies to `cromwell-tools`, making it more than a simple standalone Python API of Cromwell. Specifically, besides dealing with the response error codes from Cromwell, we will need to parse and real with various possible errors raised by the validation WDL(I guess?).
    - I agree this feature could live in the `cromwell-tools` code base, but it'd be better to put this feature/tool separate from the core APIs(submit/abort/query/) that are mapped from Cromwell endpoints and make it optional. 
    -  I'm not familiar with the validation WDL here, but given the broad uses cases of the WDL, I assume it must be portable to nearly most of the workflows and just simply checks the checksums/sizes/existence of the WDL. So if I'm correct here, can we simplify th checks/validations and make them happen in Python rather than in WDL/Cromwell? If I'm wrong here, it will get more complicated, we might end up having overhead like how to version control the validation WDL with the Python lib, how to make it compatible to all workflows, etc...

**Comment by danxmoran** [comment]
👍 to a separate module for test utilities. Am also open to tweaking the naming.

Some clarifications:

The goal is to push all custom logic for checking the outputs of a pipeline into a corresponding validation WDL, so the code in the test framework doesn't have to be extended for every new pipeline. For example, [here's](https://github.com/broadinstitute/dsde-pipelines/blob/develop/genomes_in_the_cloud/single_sample/verifySSWF.wdl) the validation WDL used by Green for the germline single-sample workflow, and [here's](https://github.com/broadinstitute/dsde-pipelines/blob/develop/genomes_in_the_cloud/arrays/VerifyArraysWf.wdl) the workflow they use the validate the genotyping arrays workflow. The comparisons performed are usually more complicated than a bitwise diff, so you end up wanting to run the logic in the cloud.

To *really* make the test harness work for any given scientific-WDL/validation-WDL pair, we'd need to rely on some convention about how the outputs of the scientific WDL map to the inputs of the validation WDL. As a rough idea, we could say if your scientific WDL has outputs:
```wdl
output {
  Int my_int_output
  Array[String] my_string_array_output
  File my_file_output
}
```
Then the paired validation WDL should know about a struct of the shape:
```wdl
struct ExpectedOutputs {
  Int my_int_output
  Array[String] my_string_array_output
  File my_file_output
}
```
And take as input:
```wdl
input {
  ExpectedOutputs test_outputs
  ExpectedOutputs truth_outputs
}
```
The test runner could then have some generic logic that transforms output JSON of the scientific WDL into input JSON for the validation WDL.

A less magical alternative would be to have the validation WDL take the raw outputs JSON from the scientific WDL as input:
```wdl
input {
  # i.e. "{\"MyWorkflow.my_int_output\":1,\"MyWorkflow.my_string_array_output\":[],\"MyWorkflow.my_file_output\":\"gs://path/to/the/file.bam\"}"
  String escaped_test_output_json
  String escaped_truth_output_json
}
```
The first task in validation would then have to parse the JSONs and extract out the data-to-compare.

For watching/interpreting validation outputs, an easy first pass would push the work onto the validation-WDL-write by setting up another convention: if test outputs don't match truth outputs, the validation WDL should fail. Then a generic wrapper around the existing `wait` command would be enough to catch failures.

**Comment by danxmoran** [comment]
I looked at how Mint currently handles this style of testing. They use subworkflows, with the checker WDL importing and running the scientific WDL as its first step. This has the benefits of:
* Not needing magic conventions to thread scientific outputs into checker inputs
* Not needing extra code in `cromwell-tools`

So, closing this!
