### ISSUE TITLE
missing comma in setup.py ?

### ISSUE THREAD

**Issue by notestaff** [broadinstitute/cromwell-tools#84]
at https://github.com/broadinstitute/cromwell-tools/blame/master/setup.py#L19
seems a comma is missing?  @rexwangcc @samanehsan

**Comment by rexwangcc** [comment]
@notestaff Thanks, this is a good catch. Luckily that extra comma didn't affect the installation of `google-auth` but `'\setuptools_scm` which influence the development only. While I'm wondering why it was not captured by the linters, a quick fix should be ready shortly. 

Thanks again!
