### ISSUE TITLE
Broken link in Read The Docs

### ISSUE THREAD

**Issue by kbergin** [broadinstitute/cromwell-tools#90]
The [Read the Docs ](https://cromwell-tools.readthedocs.io/en/latest/README_SYMLINK.html#python-api) has a link to a quickstart jupyter notebook tutorial and the link is currently broken in both stable and latest.

**Comment by rexwangcc** [comment]
@kbergin Thanks for catching this! The [docs](https://cromwell-tools.readthedocs.io/en/latest/README_SYMLINK.html#python-api) now has the rendered Jupyter Notebooks built-in, which could be found from the left-panel, but we should remove the broken link or redirect to the new place!
